### PR TITLE
Allow users of the step to offset versionCode, and generate version info output

### PR DESCRIPTION
**Pull request by koklitheen**
**Added an optional input to offset versionCode**

When uploading a new Android build to the Play Store, the versionCode number value cannot be lesser than a previously published build. It’d be useful for this step to take in an optional offset value to offset the versionCode just like the Bundle Version Offset in the iOS counterpart step https://github.com/BOOMik/steps-set-ios-version. 

In our Android apps on bitrise.io, we use this step by setting new version code to `$BITRISE_BUILD_NUMBER`.  However, this is not enough if we were to migrate some of our existing projects to use bitrise.io as our continuous deployment tool as they have existing published builds with higher versionCode.

**Generate ANDROID_VERSION_NAME and ANDROID_VERSION_CODE output** 

So that, steps after it can make use of their values. These output values are extremely useful especially for steps like Slack integration to include build version info.

Hope you will consider my changes and include them in your step! :)

### CODE REVIEW

**Comment by koklitheen** [comment]
So as it turns out, this PR failed the CI check but I'm not able to see what the failure is (getting a 403). I'd be happy to fix it if I know what the problem is. I've run `bitrise run test` before issuing this PR and the test came out fine.

**Comment by bootstraponline** [comment]
> Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.
ERROR: manual merge, error: merge failed (fork/master), error: exit status 1
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | git-clone (exit code: 1)                                      | 3.69 sec |
+---+---------

**Comment by viktorbenei** [comment]
Thanks for the PR @koklitheen !

It seems this step's CI process has a setup issue, that's why it failed. We'll fix that ASAP and review your PR! :)

**Comment by viktorbenei** [comment]
Actually, I'd argue against adding this feature to this step directly.

> In our Android apps on bitrise.io, we use this step by setting new version code to $BITRISE_BUILD_NUMBER.

Definitely see your point but IMO this should not be handled in this step directly.

The right solution is to offset the build number itself! You can do that with the **Adjust BuildNumber** step for example.

Why that's a better solution? Because that way the $BITRISE_BUILD_NUMBER will be changed for all subsequent steps, not just for this specific step. This means that if you e.g. send a Slack message you can include the modified build number there too.

Is there a reason why you'd want to only change the build number in this step exclusively, and not in other parts of the build @koklitheen ?

**Comment by koklitheen** [comment]
@viktorbenei Wow, I did not know about **Adjust BuildNumber** step! Apologies for the ignorance. Yes, I'd agree that **Adjust BuildNumber** would have been a better place to offset the versionCode. 

It may still be useful to get the versionName and versionCode in an output variable though. Any thoughts? :)

**Comment by viktorbenei** [comment]
> It may still be useful to get the versionName and versionCode in an output variable though. Any thoughts? :)

Definitely! ;)

**Comment by godrei** [comment]
Hi @koklitheen ,
thanks for the PR! t
The versions setter step for ios has the same [offset feature](https://github.com/bitrise-io/bitrise-steplib/blob/master/steps/set-ios-version/2.0.0/step.yml#L48), so i can agree with these changes.

**Pull request merged**
